host: 0.0.0.0
collections:
  chapters:
    output: true
    permalink: /chapter/:path
  teams:
    output: true
    permalink: /team/:path

sass:
  style: compressed

permalink: pretty
exclude: [vendor]
plugins:
  - jekyll-sitemap
  - jekyll-minifier

jekyll-minifier:
  uglifier_args:
    harmony: true

